### Input tensor($N, C_{in}, H_{in}, W_{in}$)
 - $N$: batch size
 - $C_{in}$ : in_channerls
 - $H_{in}$ : 2D input tensor height
 - $ W_{in}$:  2D input tensor width

### Output size
 ![image.png](http://drive.google.com/uc?id=12reHf9xtapZrVBG4LlNbNGa37ZeFfUqk)

In [1]:
import torch
import torch.nn as nn

input = torch.ones(1,1,4,4)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 2, 2])


In [2]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 2, 2])


In [3]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=4, stride=1, padding=2)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 6, 6])


In [4]:
input = torch.ones(1,1,6,6)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 3, 3])


In [5]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 5, 5])


In [6]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 3, 3])


In [7]:
input = torch.ones(1,1,5,5)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=2)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 7, 7])


In [8]:
input = torch.ones(1,3,5,5)
conv_layer = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, stride=2, padding=1)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 3, 3, 3])


In [9]:
input = torch.ones(1,1,6,6)
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0)
output = conv_layer(input)

print(output.shape)

torch.Size([1, 1, 2, 2])


In [10]:
INPUT_SIZE = (227,227)
IN_CHANNELS = 3
OUT_CHANNELS = 10
KERNEL_SIZE = 11
STRIDE = 4
PADDING = 0

input = torch.ones(1,IN_CHANNELS,INPUT_SIZE[0],INPUT_SIZE[1])
func = nn.Conv2d(in_channels=IN_CHANNELS, out_channels=OUT_CHANNELS, kernel_size=KERNEL_SIZE, stride=STRIDE, padding=PADDING)
output = func(input)

print(output.shape)

torch.Size([1, 10, 55, 55])


In [11]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

func = nn.MaxPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[6., 8.],
         [3., 4.]]])


In [12]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]])
print(input)

func = nn.AvgPool2d(kernel_size=2)
output = func(input)
print(output)

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[2.7500, 4.7500],
         [1.7500, 1.7500]]])


In [13]:
input = torch.tensor([[[1.,0.,2.,3.],[4.,6.,6.,8.],[3.,1.,1.,0.],[1.,2.,2.,4.]]]) # shpae : [1,4,4]
print(input)

# kernel_size, stride, padding을 입력하는 대신에 output의 사이즈를 입력
# 위의 식에 따라서 자동으로 kernel_size, stride, padding이 결정되어 pooling을 할 수 있음.
func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output) # shape : [1,1,1]

tensor([[[1., 0., 2., 3.],
         [4., 6., 6., 8.],
         [3., 1., 1., 0.],
         [1., 2., 2., 4.]]])
tensor([[[2.7500]]])


In [14]:
input = torch.randn((1,3,4,4))
print(input)

func = nn.AdaptiveAvgPool2d(1)
output = func(input)
print(output)

tensor([[[[ 1.1358, -0.4860, -1.8319, -0.4489],
          [ 1.1558,  0.2675, -0.2777,  0.3188],
          [ 0.4887,  0.0254, -0.0799,  1.6214],
          [ 0.2664,  0.2437,  0.4042, -1.0725]],

         [[-0.1373, -1.3475,  0.7030,  1.7158],
          [-1.0345, -2.1510,  1.2963,  0.8145],
          [-2.3135,  2.9643, -1.7261, -0.3689],
          [-0.7123, -0.6998,  2.3185, -0.6847]],

         [[-0.8528,  0.1739,  2.3470,  0.3019],
          [-1.2943, -2.8226, -0.8044,  0.5313],
          [-0.6425,  2.4071,  0.5349, -0.0153],
          [-0.1673,  0.0211,  0.5458, -1.1221]]]])
tensor([[[[ 0.1082]],

         [[-0.0852]],

         [[-0.0536]]]])


In [15]:
input = torch.randn((1,3,1,1))
print(input)

func = nn.AdaptiveAvgPool2d(7)
output = func(input)
print(output)

tensor([[[[ 0.2016]],

         [[-0.0078]],

         [[ 0.9717]]]])
tensor([[[[ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016],
          [ 0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016,  0.2016]],

         [[-0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078],
          [-0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078],
          [-0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078],
          [-0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078],
          [-0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078, -0.0078],
          [-0.0078, -0.0078,